<?php

namespace rgen3\blog\common\models;

use Yii;

/**
 * This is the model class for table "blog_tag".
 *
 * @property int $id
 * @property string $slug
 *
 * @property BlogTagTranslation[] $blogTagTranslations
 * @property BlogToTag[] $blogToTags
 * @property BlogRecord[] $records
 */
class BlogTag extends \yii\db\ActiveRecord
{
    public $translationModels = [];

    public function afterSave($insert, $changedAttributes)
    {
        foreach ($this->translationModels as $language => $translation)
        {
            $translation->tag_id = $this->id;
            $translation->language_code = $language;
            $translation->save();
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%blog_tag}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['slug'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'slug' => Yii::t('app', 'Slug'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBlogTagTranslations()
    {
        return $this->hasMany(BlogTagTranslation::className(), ['tag_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBlogToTags()
    {
        return $this->hasMany(BlogToTag::className(), ['tag_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecords()
    {
        return $this->hasMany(BlogRecord::className(), ['id' => 'record_id'])->viaTable('blog_to_tag', ['tag_id' => 'id']);
    }

    public function getTranslation($lang = null)
    {
        if (is_null($lang))
        {
            $lang = Yii::$app->language;
        }

        $model = BlogTagTranslation::findOne(['tag_id' => $this->id, 'language_code' => $lang]);

        if (!$model)
        {
            $model = new BlogTagTranslation();
        }

        return $model;
    }
}
