<?php

namespace rgen3\blog\frontend\widgets;

use rgen3\blog\common\models\BlogRecord;
use rgen3\blog\common\models\BlogRecordSearch;
use yii\base\Widget;

class RecordList extends Widget
{
    public $viewPath = null;
    public $template = null;
    public $limit = 10;
    public $offset = 0;
    public $category = null;
    public $orderBy = [];

    public $title = 'News';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::setAlias( '@blog/frontend',  dirname(__DIR__));
    }

    public function run()
    {
        $model = new BlogRecordSearch();
        $dataProvider = $model->search([
            'limit' => $this->limit,
            'offset' => $this->offset,
            'category' => $this->prepareCategory(),
            'orderBy'      => $this->prepareSort()
        ]);
        return $this->render($this->getTemplate(), [
            'dataProvider' => $dataProvider,
            'blockHeading' => $this->title
        ]);
    }

    public function getViewPath()
    {
        return \Yii::getAlias($this->viewPath ?? '@blog/frontend/views/widgets/recordList');
    }

    private function getTemplate()
    {
        $template = $this->template;
        if (is_null($template))
        {
            $template = 'defaultNewsList.php';
        }

        return $template;
    }

    private function prepareCategory()
    {
        $categories = $this->category;

        if (!is_array($categories) && !is_null($categories))
        {
            $categories = [$categories];
        }

        return $categories;
    }

    private function prepareSort()
    {
        if (!is_array($this->orderBy))
            throw new \InvalidArgumentException();

        return $this->orderBy;
    }
}